modLoader = "javafml"
loaderVersion = "[47,)"
license = "WTFPL"
[[mods]]
modId = "semishigure"
version = "0.2"
displayName = "Semishigure"
authors = "LocusAzzurro"
description = '''

'''
[[dependencies.semishigure]]
modId = "forge"
mandatory = true
versionRange = "[47.1,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.semishigure]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"
